### ISSUE TITLE
 module 'headers' has no attribute 'headers'

### ISSUE THREAD

**Issue by LucretiaAudrey** [WKS-uwu/WKS-KEY#1]
Installed all the stuff. trying random disney plus video
Got pssh, license request url
Getting error: module 'headers' has no attribute 'headers'

D:\WKS-KEYS>D:\WKS-KEYS\l3.py

PSSH: AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABISELw5WnrhcE3qv3GCfiskdXU=
License URL: https://disney.playback.edge.bamgrid.com/widevine/v1/obtain-license

Traceback (most recent call last):
  File "D:\WKS-KEYS\l3.py", line 25, in <module>
    correct, keys = WV_Function(pssh, lic_url)
  File "D:\WKS-KEYS\l3.py", line 19, in WV_Function
    widevine_license = requests.post(url=lic_url, data=wvdecrypt.get_challenge()
, headers=headers.headers)
AttributeError: module 'headers' has no attribute 'headers'

**Comment by p2mgrup** [comment]
you provided a header in header.py?
Please check this CURL screens.

**Comment by WKS-uwu** [comment]
yeah, as the one above said
update header in header.py?

**Comment by ufo56** [comment]
Whats PSSH?

**Comment by LucretiaAudrey** [comment]
Works for Disney now
