### ISSUE TITLE
Mubi - "unable to parse license - check protobufs" despite correct pssh, license server, and headers 

### ISSUE THREAD

**Issue by six-eleven** [WKS-uwu/WKS-KEY#15]
I'm sure I've done everything correctly - double checked pssh both thru decoding the license request printed by EME logger, and checking it with mp4dump of the init segment. 

And when doing a request to the license server with the given pssh and headers, it actually returns what I take to be a proper license, eg
```
{"status":"OK","status_message":"","license":"CAIS7AIKWgogRDg0QjUwQUQ4NTA5NDZENzAxMDAwMDAwMDAwMDAwMDASIEQ4NEI1MEFEODUwOTQ2RDcwMTAwMDAwMDAwMDAwMDAwGgAgASgAOP/IuAFA/8i4AUjMsrWNBhIXCAEQARgAIP/IuAEo/8i4ATD+kfECYAEaZhIQM3CeAmQ+DGQSNiZngD1xThpQ6GoD6VEzIXSnAM1hulPka7K5lZ/LXn3xKhZ9DRyNpmdWtY4Umzg0gM3Nm0krMRtm4lv/73LG2POxSIdKiOBr7zaDh3IduQ0BPrZpIli7OnQgARqEAQoQpvpK8Wv4SC2NmCXhymTm5RIQfNUPOY7cArahbxzolsT5nBogBrb9dmkXi16C9qZ3nW0MV5t0P98MLlCeMvExsLsZj+IgAigBQjQKIPwWhrGhmVlPWQTl6K/5+974ViMp1gUc0UElb2qHukbxEhDVfz4EAx5X24W0tS3QqyQPYgJIRCDMsrWNBjgAGiAOJ03iE1oixLFr6x4pAH+n20v3Jqh9t0o/NmhocVIa3CKAAr4xLkACUbCx5b9FKGkv2TU8RtU22q5WPz75IVY2tQZen1LLVkGGYdKtgqtdSTiWMyPBrXhHPOMpXReAFT48UDToQMBjWDgHl7M6ZHDWRxhvLH4VYhQdepoJlb3YNvLWyndgzmVGO/kI6y2P6ZtxvTyN5n1nBRHtGGGdY1fbnXaRkwVpIs1zwFc309NLCII7dJxGdprf5c+VMrl0sNi9u7CmM2i9gAzx6ce3i7mFnT/tPUn6qMZAJNg0LJNa4lczaUdwVAof9BsgMM2tnGpuwyFqCU+H09wERMzF9M4HwFW90VHXOCWp/FSP6Q1oAhZFkn66j9e80VGNAjtL8zTFI846MwoxMTYuNC41IEJ1aWx0IG9uIEp1biAyNCAyMDIxIDIxOjM5OjA4ICgxNjI0NTk1OTEyKUABWAA=","license_metadata":{"content_id":"cHZwSzhXdjRTQzJObUNYaHltVG01UT09","license_type":"STREAMING","request_type":"NEW"},"supported_tracks":[{"type":"HD","key_id":"pvpK8Wv4SC2NmCXhymTm5Q=="}],"make":"Generic Field Provisioning","model":"Android KLP x86","security_level":3,"internal_status":0,"session_state":{"license_id":{"request_id":"RDg0QjUwQUQ4NTA5NDZENzAxMDAwMDAwMDAwMDAwMDA=","session_id":"RDg0QjUwQUQ4NTA5NDZENzAxMDAwMDAwMDAwMDAwMDA=","purchase_id":"","type":"STREAMING","version":0,"original_rental_duration_seconds":3023999,"original_playback_duration_seconds":3023999,"original_start_time_seconds":1638750540},"signing_key":"yAPLX1j0MqbW8UZ9X2ulJHvAHXjWQxLGn+UEBi7L8uxheOAeFPGT1fpNDvVSKU2fofMsPeloeTrtiiENKSXtYA==","keybox_system_id":4464,"license_counter":0},"drm_cert_serial_number":"Zjc5NTNkZTViMjgyMTJlMzRlYTI0MTU0ZjBlYTYzNmM=","device_whitelist_state":"DEVICE_WHITELISTED","message_type":"LICENSE","platform":"android","device_state":"RELEASED","pssh_data":{"key_id":["pvpK8Wv4SC2NmCXhymTm5Q=="],"content_id":"cHZwSzhXdjRTQzJObUNYaHltVG01UT09"},"client_max_hdcp_version":"HDCP_NONE","client_info":[{"name":"company_name","value":"Google"},{"name":"model_name","value":"Android SDK built for x86"},{"name":"architecture_name","value":"x86"},{"name":"device_name","value":"generic_x86"},{"name":"product_name","value":"sdk_google_phone_x86"},{"name":"build_info","value":"google/sdk_google_phone_x86/generic_x86:7.1.1/NYC/5464897:userdebug/test-keys"},{"name":"device_id","value":"zdfDCPHaHrBQakqKhEcFqXiLwbblJwg\\u0000"},{"name":"widevine_cdm_version","value":"v4.1.0-android"},{"name":"oem_crypto_security_patch_level","value":"0"}],"platform_verification_status":"PLATFORM_NO_VERIFICATION","content_owner":"castlabs","content_provider":"castlabs","system_id":4464,"oem_crypto_api_version":11,"resource_rating_tier":0,"service_version_info":{"license_sdk_version":"16.4.5 Built on Jun 24 2021 21:39:08 (1624595912)","license_service_version":"widevine_license_wls_20210624_212492-RC00"},"soc":"android generic"}
```

However that message, `unable to parse license - check protobufs` still appears regardless. I somewhat traced the error to this code block in cdm.py

```python
license = wv_proto2.SignedLicense()
        try:
            license.ParseFromString(base64.b64decode(license_b64))
        except DecodeError:
            self.logger.error("unable to parse license - check protobufs")
            return 1
```

Issue seems to be that this SignedLicense function doesn't actually return anything, and with nothing assigned to the license variable it cannot be decoded, resulting in the aforementioned error.

Not sure how to procceed from here, I checked the proto file and the SignedLicense part of it, but didn't understand much of anything

**Comment by naim2007** [comment]
You need to edit pywidevine code format,
change the request,
request only license: CAES...... & base64 decode it.
get keys... easy pz

**Comment by monat78** [comment]
hi naim... what is CAES?

**Comment by medvm** [comment]
Hi six-eleven. Since you closed this issue, have you got it all right?

**Comment by chriskeens** [comment]
> I'm sure I've done everything correctly - double checked pssh both thru decoding the license request printed by EME logger, and checking it with mp4dump of the init segment.
> 
> And when doing a request to the license server with the given pssh and headers, it actually returns what I take to be a proper license, eg
> 
> ```
> {"status":"OK","status_message":"","license":"CAIS7AIKWgogRDg0QjUwQUQ4NTA5NDZENzAxMDAwMDAwMDAwMDAwMDASIEQ4NEI1MEFEODUwOTQ2RDcwMTAwMDAwMDAwMDAwMDAwGgAgASgAOP/IuAFA/8i4AUjMsrWNBhIXCAEQARgAIP/IuAEo/8i4ATD+kfECYAEaZhIQM3CeAmQ+DGQSNiZngD1xThpQ6GoD6VEzIXSnAM1hulPka7K5lZ/LXn3xKhZ9DRyNpmdWtY4Umzg0gM3Nm0krMRtm4lv/73LG2POxSIdKiOBr7zaDh3IduQ0BPrZpIli7OnQgARqEAQoQpvpK8Wv4SC2NmCXhymTm5RIQfNUPOY7cArahbxzolsT5nBogBrb9dmkXi16C9qZ3nW0MV5t0P98MLlCeMvExsLsZj+IgAigBQjQKIPwWhrGhmVlPWQTl6K/5+974ViMp1gUc0UElb2qHukbxEhDVfz4EAx5X24W0tS3QqyQPYgJIRCDMsrWNBjgAGiAOJ03iE1oixLFr6x4pAH+n20v3Jqh9t0o/NmhocVIa3CKAAr4xLkACUbCx5b9FKGkv2TU8RtU22q5WPz75IVY2tQZen1LLVkGGYdKtgqtdSTiWMyPBrXhHPOMpXReAFT48UDToQMBjWDgHl7M6ZHDWRxhvLH4VYhQdepoJlb3YNvLWyndgzmVGO/kI6y2P6ZtxvTyN5n1nBRHtGGGdY1fbnXaRkwVpIs1zwFc309NLCII7dJxGdprf5c+VMrl0sNi9u7CmM2i9gAzx6ce3i7mFnT/tPUn6qMZAJNg0LJNa4lczaUdwVAof9BsgMM2tnGpuwyFqCU+H09wERMzF9M4HwFW90VHXOCWp/FSP6Q1oAhZFkn66j9e80VGNAjtL8zTFI846MwoxMTYuNC41IEJ1aWx0IG9uIEp1biAyNCAyMDIxIDIxOjM5OjA4ICgxNjI0NTk1OTEyKUABWAA=","license_metadata":{"content_id":"cHZwSzhXdjRTQzJObUNYaHltVG01UT09","license_type":"STREAMING","request_type":"NEW"},"supported_tracks":[{"type":"HD","key_id":"pvpK8Wv4SC2NmCXhymTm5Q=="}],"make":"Generic Field Provisioning","model":"Android KLP x86","security_level":3,"internal_status":0,"session_state":{"license_id":{"request_id":"RDg0QjUwQUQ4NTA5NDZENzAxMDAwMDAwMDAwMDAwMDA=","session_id":"RDg0QjUwQUQ4NTA5NDZENzAxMDAwMDAwMDAwMDAwMDA=","purchase_id":"","type":"STREAMING","version":0,"original_rental_duration_seconds":3023999,"original_playback_duration_seconds":3023999,"original_start_time_seconds":1638750540},"signing_key":"yAPLX1j0MqbW8UZ9X2ulJHvAHXjWQxLGn+UEBi7L8uxheOAeFPGT1fpNDvVSKU2fofMsPeloeTrtiiENKSXtYA==","keybox_system_id":4464,"license_counter":0},"drm_cert_serial_number":"Zjc5NTNkZTViMjgyMTJlMzRlYTI0MTU0ZjBlYTYzNmM=","device_whitelist_state":"DEVICE_WHITELISTED","message_type":"LICENSE","platform":"android","device_state":"RELEASED","pssh_data":{"key_id":["pvpK8Wv4SC2NmCXhymTm5Q=="],"content_id":"cHZwSzhXdjRTQzJObUNYaHltVG01UT09"},"client_max_hdcp_version":"HDCP_NONE","client_info":[{"name":"company_name","value":"Google"},{"name":"model_name","value":"Android SDK built for x86"},{"name":"architecture_name","value":"x86"},{"name":"device_name","value":"generic_x86"},{"name":"product_name","value":"sdk_google_phone_x86"},{"name":"build_info","value":"google/sdk_google_phone_x86/generic_x86:7.1.1/NYC/5464897:userdebug/test-keys"},{"name":"device_id","value":"zdfDCPHaHrBQakqKhEcFqXiLwbblJwg\\u0000"},{"name":"widevine_cdm_version","value":"v4.1.0-android"},{"name":"oem_crypto_security_patch_level","value":"0"}],"platform_verification_status":"PLATFORM_NO_VERIFICATION","content_owner":"castlabs","content_provider":"castlabs","system_id":4464,"oem_crypto_api_version":11,"resource_rating_tier":0,"service_version_info":{"license_sdk_version":"16.4.5 Built on Jun 24 2021 21:39:08 (1624595912)","license_service_version":"widevine_license_wls_20210624_212492-RC00"},"soc":"android generic"}
> ```
> 
> However that message, `unable to parse license - check protobufs` still appears regardless. I somewhat traced the error to this code block in cdm.py
> 
> ```python
> license = wv_proto2.SignedLicense()
>         try:
>             license.ParseFromString(base64.b64decode(license_b64))
>         except DecodeError:
>             self.logger.error("unable to parse license - check protobufs")
>             return 1
> ```
> 
> Issue seems to be that this SignedLicense function doesn't actually return anything, and with nothing assigned to the license variable it cannot be decoded, resulting in the aforementioned error.
> 
> Not sure how to procceed from here, I checked the proto file and the SignedLicense part of it, but didn't understand much of anything

If you managed to fix it could you please let us know how?

**Comment by wilsonssss** [comment]
facing the same issue

**Comment by six-eleven** [comment]
just the license part needs to be provided to the cdm, so
`license_b64 = json.loads(widevine_license.content.decode())['license']` or some such works instead of giving the whole license response with `license_b64 = b64encode(widevine_license.content)`
